galaxy_info:
  author: Bruno Cochofel
  description: Creates the elastic-system namespace and Fleet enrollment Secret for the elastic-agent GitOps app
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags: []
dependencies: []
