galaxy_info:
  author: Bruno Cochofel
  description: Installs Cilium (CNI + kube-proxy replacement + Hubble) via the official cilium CLI
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags: []
dependencies: []
